### ISSUE TITLE
`game-versions` cannot take variables

### ISSUE THREAD

**Issue by NoComment1105** [Kir-Antipov/mc-publish#1]
When an action using this action, i have been trying to use a github actions step to allow me to get the version file from my `gradle.properties` however the game-version does not accept such variables. An example follows
```yml 
name: build-release

on:
  release:
    types:
      - published

jobs:
  get-properties:
    runs-on: ubuntu-latest
    outputs:
      minecraft-version: ${{ steps.properties.outputs.minecraft_version }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Read version from gradle.properties
        id: properties
        run: |
          path='./gradle.properties'
          for property in minecraft_version
          do
            result=$(sed -n "/^[[:space:]]*$property[[:space:]]*=[[:space:]]*/s/^[[:space:]]*$property[[:space:]]*=[[:space:]]*//p" "$path")
            echo "$property: $result"
            echo ::set-output name=$property::"$result"
          done
  build:
    runs-on: ubuntu-latest
    needs: [get-properties]
    steps:
      - name: Get version info
        id: getversioninfo
        run: |
          echo "::set-output name=version::${{ needs.get-properties.outputs.minecraft_version }}"
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 16
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/loom-cache
            ~/.gradle/wrapper
            ~/.m2/repository
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - run: chmod +x gradlew

      - name: Build Release
        run: ./gradlew build --stacktrace

      - name: Upload artifacts to Modrinth, Curseforge and GitHub
        uses: Kir-Antipov/mc-publish@v1.1
        with:
          modrinth-id:
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}

          files: build/libs/!(*-@(dev|sources|all)).jar

          version-type: release

          loaders: fabric

          game-versions: ${{ steps.getversioninfo.outputs.minecraft_version }}
```
will not be accepted even though the value it returns (in this use case) is `1.16.5`, which is clearly listed as a valid string in your documentation. 

I would like to request that game-versions accepts such strings, since it's a great benefit to not have to update the action between each version, since im quite prone to forgetting :)

**Comment by Kir-Antipov** [comment]
What does `cannot take variables` actually mean? GitHub resolves variables itself

**Comment by NoComment1105** [comment]
By cannot take variables i mean i refuses to take any values other than ones such as `1.16.5` or `1.18`

**Comment by NoComment1105** [comment]
In the example action it's getting the `minecraft_version` variable form the `gradle.properties` files and said variable is `1.16.5`, yet the action errors with this: 
![image](https://user-images.githubusercontent.com/67918617/145233184-a00db0f3-0695-4897-bd72-1f5b40fcd2dd.png)

**Comment by Kir-Antipov** [comment]
Wait. But the `game-versions` field is not defined judging by your screenshot

**Comment by Kir-Antipov** [comment]
```yaml
  - name: Get version info
    id: getversioninfo
    run: |
      echo "::set-output name=version::${{ needs.get-properties.outputs.minecraft_version }}"
```

The output is named `version`, isn't it? But you're trying to access it by the `minecraft_version` name
