### ISSUE TITLE
define CF and MR dependencies independently

### ISSUE THREAD

**Issue by DAmNRelentless** [Kir-Antipov/mc-publish#13]
Right now, I use the action for two steps in a row. One for each hosting platform because the dependencies that exist on CurseForge are either not existent on Modrinth or they have different slugs.

Would be cool if you could add `modrinth-dependencies` and `curseforge-dependencies` and that the normal `dependencies` option is used as common option.

**Comment by Kir-Antipov** [comment]
It works this exact way, it's just not documented ;)

The thing about GitHub Actions is you cannot pass complex objects to them as inputs, therefore I use some kind of self-built convention - inputs like `modrinth-id: id`, `modrinth-token: token` will be transformed into `{ "modrinth": { "id": "id", "token": "token" } }` object, which is an uploader-specific options object. Then it is being combined with "common" options object, which contains keys like `dependencies`, `files`, `version`, `name`, and other root entries.

Therefore, nothing really stops you from making a configuration such as this one:
```yaml
files: build/libs/build.jar # Default files value

github-token: {{ secrets.GITHUB_TOKEN }}

modrinth-id: modrinth-id
modrinth-token: {{ secrets.MODRINTH_TOKEN }}
modrinth-files: build/libs/*.jar # Modrinth-specific files, overwrites top entry of `files`
modrinth-dependencies: fabric-api # Modrinth-specific dependencies

curseforge-id: curseforge-id
curseforge-token: {{ secrets.CURSEFORGE_TOKEN }}
curseforge-files: build/libs/!(*-@(dev|sources)).jar # CurseForge-specific files, overwrites top entry of `files`
curseforge-dependencies: cloth-config # CurseForge-specific dependencies
```

I did not document this behavior because GitHub emits warnings for inputs that weren't specified in `action.yml`, and I didn't want to duplicate millions *(ok, not that many, but you've got the point)* of top-level inputs for every available uploader (`modrinth`, `curseforge`, and `github` at the moment), at least manually. I will make a script that does it automatically in the foreseen future, until then you're free to use this functionality and ignore warnings from GitHub.

Leaving this open, so I won't forget to document this feature
