### ISSUE TITLE
[Bug] Doesn't recognize `neoforge.mods.toml` if `neoforge` dependency is omitted

### ISSUE THREAD

**Issue by Kira-NT** [Kir-Antipov/mc-publish#130]
### Description

Currently, `mc-publish` doesn't recognize `neoforge.mods.toml` as a valid NeoForge metadata file if it omits the `neoforge` dependency block *(e.g., like it's done in Sodium)*:

```toml
[[dependencies.example-mod]]
    modId="neoforge"
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
```

This check was only relevant before NeoForge diverged from using the same `mods.toml` as legacy Forge. Nowadays, the mere existence of `neoforge.mods.toml` is a sufficient indicator that the mod supports NeoForge.

### Expected Behavior

`mc-publish` should be able to read `neoforge.mods.toml` even if it doesn't explicitly specify the `neoforge` dependency block.

### Actual Behavior

`mc-publish` fails to read `neoforge.mods.toml` if the `neoforge` dependency block is omitted, effectively disabling automatic property resolution.

### Version

v3

### Environment

GitHub Actions
