### ISSUE TITLE
[Bug] GitHub API failure? "You have sent an invalid request. Please do not send this request again."

### ISSUE THREAD

**Issue by IMB11** [Kir-Antipov/mc-publish#137]
### Description

```Markdown
https://github.com/IMB11/xanders-sodium-options/actions/runs/12333368646/job/34422360355

Error: HttpError: 400 (Bad Request, {"message":"You have sent an invalid request. Please do not send this request again.","request_id":"2FC0:33579C:84AFE8:912D63:675DFF3F","documentation_url":"https://developer.github.com/v3/"})
```

### Expected Behavior

It uploading to github releases.

### Actual Behavior

It doesnt.

### Version

Latest - v3.3

### Environment

GitHub Actions

### Configuration

```yml
name: Distribute JARs
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          cache: gradle
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: "8.10"
      - name: Build JARs
        uses: Wandalen/wretry.action@master
        with:
          command: "gradle chiseledBuild"
          attempt_limit: 3
      - name: Upload Built JARs
        uses: actions/upload-artifact@v4
        with:
          name: built-jars
          path: |
            ./versions/**/build/libs/*.jar
  distribute:
    needs: build
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        game_version: [ "1.21.1", "1.21.3", "1.21.4" ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Download Built JARs
        uses: actions/download-artifact@v4
        with:
          name: built-jars
          path: ./versions
      - name: Publish to Modrinth, CurseForge, etc.
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          files: |
            versions/${{ matrix.game_version }}/build/libs/!(*-@(dev|sources|javadoc)).jar
            versions/${{ matrix.game_version }}/build/libs/*-@(dev|sources|javadoc).jar
          version: ${{ github.ref_name }}+${{ matrix.game_version }}
          modrinth-id: ${{ vars.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: ${{ vars.CURSEFORGE_ID }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.CLASSIC_GITHUB_TOKEN }}
```

### Logs

```sh
Run Kir-Antipov/mc-publish@v3.3
  with:
    files: versions/1.21.1/build/libs/!(*-@(dev|sources|javadoc)).jar
  versions/1.21.1/build/libs/*-@(dev|sources|javadoc).jar
  
    version: 2.3.0+1.21.1
    modrinth-id: sTkQBVyo
    modrinth-token: ***
    curseforge-id: 678306
    curseforge-token: ***
    modrinth-featured: ${undefined}
    modrinth-unfeature-mode: subset
    github-tag: ${undefined}
    github-generate-changelog: ${undefined}
    github-draft: ${undefined}
    github-prerelease: ${undefined}
    github-commitish: ${undefined}
    github-discussion: ${undefined}
    files-primary: ${undefined}
    files-secondary: ${undefined}
    name: ${undefined}
    version-type: ${undefined}
    changelog: ${undefined}
    changelog-file: ${undefined}
    loaders: ${undefined}
    game-versions: ${undefined}
    dependencies: ${undefined}
    version-resolver: ${undefined}
    game-version-filter: releases
    java: ${undefined}
    retry-attempts: 2
    retry-delay: 10000
    fail-mode: fail
    modrinth-files: ${undefined}
    curseforge-files: ${undefined}
    github-files: ${undefined}
    modrinth-files-primary: ${undefined}
    curseforge-files-primary: ${undefined}
    github-files-primary: ${undefined}
    modrinth-files-secondary: ${undefined}
    curseforge-files-secondary: ${undefined}
    github-files-secondary: ${undefined}
    modrinth-name: ${undefined}
    curseforge-name: ${undefined}
    github-name: ${undefined}
    modrinth-version: ${undefined}
    curseforge-version: ${undefined}
    github-version: ${undefined}
    modrinth-version-type: ${undefined}
    curseforge-version-type: ${undefined}
    github-version-type: ${undefined}
    modrinth-changelog: ${undefined}
    curseforge-changelog: ${undefined}
    github-changelog: ${undefined}
    modrinth-changelog-file: ${undefined}
    curseforge-changelog-file: ${undefined}
    github-changelog-file: ${undefined}
    modrinth-loaders: ${undefined}
    curseforge-loaders: ${undefined}
    github-loaders: ${undefined}
    modrinth-game-versions: ${undefined}
    curseforge-game-versions: ${undefined}
    github-game-versions: ${undefined}
    modrinth-dependencies: ${undefined}
    curseforge-dependencies: ${undefined}
    github-dependencies: ${undefined}
    modrinth-version-resolver: ${undefined}
    curseforge-version-resolver: ${undefined}
    github-version-resolver: ${undefined}
    modrinth-game-version-filter: ${undefined}
    curseforge-game-version-filter: ${undefined}
    github-game-version-filter: ${undefined}
    modrinth-java: ${undefined}
    curseforge-java: ${undefined}
    github-java: ${undefined}
    modrinth-retry-attempts: ${undefined}
    curseforge-retry-attempts: ${undefined}
    github-retry-attempts: ${undefined}
    modrinth-retry-delay: ${undefined}
    curseforge-retry-delay: ${undefined}
    github-retry-delay: ${undefined}
    modrinth-fail-mode: ${undefined}
    curseforge-fail-mode: ${undefined}
    github-fail-mode: ${undefined}
📤 Uploading assets to CurseForge
✅ Successfully published assets to CurseForge in 1699 ms
📤 Uploading assets to Modrinth
🔽 Initiating unfeaturing of older Modrinth project versions
✅ Successfully published assets to Modrinth in 1660 ms
📤 Uploading assets to GitHub
Error: HttpError: 400 (Bad Request, {"message":"You have sent an invalid request. Please do not send this request again.","request_id":"2FC0:33579C:84AFE8:912D63:675DFF3F","documentation_url":"https://developer.github.com/v3/"})
```
