### ISSUE TITLE
[Bug] File extension is invalid for input file (Modrinth)

### ISSUE THREAD

**Issue by kylelaverty** [Kir-Antipov/mc-publish#141]
### Description

```Markdown
I am trying to bundle my data pack and upload it to Modrinth. I have been able to zip it and used ls to confirm it is in the root directory with the name I expect. When the action tries to upload a 400 is thrown.

I may have misconfigured something as this is the first data pack I have tried to upload.
```

### Expected Behavior

I am able to create a new version

### Actual Behavior

`Error: HttpError: 400 (Bad Request, {"error":"invalid_input","description":"Error with multipart data: File extension is invalid for input file"})`

### Version

3.3

### Environment

GitHub Actions

### Configuration

```yml
name: build

on:
  push:
    branches: ["main"]
    paths-ignore: ["**.md", "**/assets/modrinth/**"]
  pull_request:
    branches: ["main"]
    paths-ignore: ["**.md", "**/assets/modrinth/**"]

env:
  MINECRAFT_VERSION: 1.20.1
  JAVA_VERSION: 1.17
  VERSION: mc1.20.1-0.0.1-beta-fabric
  VERSION_TYPE: beta
  RELEASE_NAME: 0.0.1 (beta) for Fabric 1.20.1
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check JSON
        uses: ocular-d/json-linter@0.0.2

      - name: Zip Data Pack
        uses: TheDoctor0/zip-release@0.7.6
        with:
          filename: "villagerplusmasontrades-${{env.VERSION}}.zip"
          exclusions: "*.git* /*assets/* .gitignore LICENSE README.md"

      - name: List Files
        run: ls -R

      # Only publish on push to main branch
      - name: Publish Build Artifacts to GitHub Release and Modrinth

        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: HxZExx2V
          modrinth-token: "${{env.MODRINTH_TOKEN}}"
          github-token: "${{env.GITHUB_TOKEN}}"
          github-tag: "${{env.VERSION}}"
          files: "./villagerplusmasontrades-${{env.VERSION}}.zip"
          name: "${{env.RELEASE_NAME}}"
          version: "${{env.VERSION}}"
          version-type: "${{env.VERSION_TYPE}}"
          loaders: fabric
          game-versions: "${{env.MINECRAFT_VERSION}}"
          dependencies: |
            villagersplus(required){modrinth:oHGMwNDR}
            lets-do-meadow(required){modrinth:ra7o6Sl7}
            supplementaries(required){modrinth:fFEIiSDQ}
          java: "${{env.JAVA_VERSION}}"
```

### Logs

```sh
Run Kir-Antipov/mc-publish@v3.3
  with:
    modrinth-id: HxZExx2V
    modrinth-token: ***
    github-token: ***
    github-tag: vmc1.20.1-0.0.1-beta-fabric
    files: ./villagerplusmasontrades-mc1.20.1-0.0.1-beta-fabric.zip
    name: 0.0.1 (beta) for Fabric 1.20.1
    version: mc1.20.1-0.0.1-beta-fabric
    version-type: beta
    loaders: fabric
    game-versions: 1.20.1
    dependencies: villagersplus(required){modrinth:oHGMwNDR}
  lets-do-meadow(required){modrinth:ra7o6Sl7}
  supplementaries(required){modrinth:fFEIiSDQ}
  
    java: 1.17
    modrinth-featured: ${undefined}
    modrinth-unfeature-mode: subset
    curseforge-id: ${undefined}
    curseforge-token: ${undefined}
    github-generate-changelog: ${undefined}
    github-draft: ${undefined}
    github-prerelease: ${undefined}
    github-commitish: ${undefined}
    github-discussion: ${undefined}
    files-primary: ${undefined}
    files-secondary: ${undefined}
    changelog: ${undefined}
    changelog-file: ${undefined}
    version-resolver: ${undefined}
    game-version-filter: releases
    retry-attempts: 2
    retry-delay: 10000
    fail-mode: fail
    modrinth-files: ${undefined}
    curseforge-files: ${undefined}
    github-files: ${undefined}
    modrinth-files-primary: ${undefined}
    curseforge-files-primary: ${undefined}
    github-files-primary: ${undefined}
    modrinth-files-secondary: ${undefined}
    curseforge-files-secondary: ${undefined}
    github-files-secondary: ${undefined}
    modrinth-name: ${undefined}
    curseforge-name: ${undefined}
    github-name: ${undefined}
    modrinth-version: ${undefined}
    curseforge-version: ${undefined}
    github-version: ${undefined}
    modrinth-version-type: ${undefined}
    curseforge-version-type: ${undefined}
    github-version-type: ${undefined}
    modrinth-changelog: ${undefined}
    curseforge-changelog: ${undefined}
    github-changelog: ${undefined}
    modrinth-changelog-file: ${undefined}
    curseforge-changelog-file: ${undefined}
    github-changelog-file: ${undefined}
    modrinth-loaders: ${undefined}
    curseforge-loaders: ${undefined}
    github-loaders: ${undefined}
    modrinth-game-versions: ${undefined}
    curseforge-game-versions: ${undefined}
    github-game-versions: ${undefined}
    modrinth-dependencies: ${undefined}
    curseforge-dependencies: ${undefined}
    github-dependencies: ${undefined}
    modrinth-version-resolver: ${undefined}
    curseforge-version-resolver: ${undefined}
    github-version-resolver: ${undefined}
    modrinth-game-version-filter: ${undefined}
    curseforge-game-version-filter: ${undefined}
    github-game-version-filter: ${undefined}
    modrinth-java: ${undefined}
    curseforge-java: ${undefined}
    github-java: ${undefined}
    modrinth-retry-attempts: ${undefined}
    curseforge-retry-attempts: ${undefined}
    github-retry-attempts: ${undefined}
    modrinth-retry-delay: ${undefined}
    curseforge-retry-delay: ${undefined}
    github-retry-delay: ${undefined}
    modrinth-fail-mode: ${undefined}
    curseforge-fail-mode: ${undefined}
    github-fail-mode: ${undefined}
  env:
    MINECRAFT_VERSION: 1.20.1
    JAVA_VERSION: 1.17
    VERSION: mc1.20.1-0.0.1-beta-fabric
    VERSION_TYPE: beta
    RELEASE_NAME: 0.0.1 (beta) for Fabric 1.20.1
    MODRINTH_TOKEN: ***
    GITHUB_TOKEN: ***
📤 Uploading assets to Modrinth
Error: HttpError: 400 (Bad Request, {"error":"invalid_input","description":"Error with multipart data: File extension is invalid for input file"})
```

### Other Information

I did try to create a new version in the Modrinth web UI using the same zip file naming without an issue.
