### ISSUE TITLE
[Bug] 400 from Modrinth

### ISSUE THREAD

**Issue by Insane96** [Kir-Antipov/mc-publish#146]
### Description

```Markdown
When trying to run the action, it fails at modrinth publishing with the following error.

Error: HttpError: 400 (Bad Request, {"error":"invalid_input","description":"Error while validating input: Field version_number failed validation with error: regex"})
```

### Expected Behavior

To publish it sucessfully

### Actual Behavior

`Error: HttpError: 400 (Bad Request, {"error":"invalid_input","description":"Error while validating input: Field version_number failed validation with error: regex"})`

### Version

3.3

### Environment

GitHub Actions

### Configuration

```yml
https://github.com/Insane96/IguanaTweaksReborn/blob/f73fb00dae7f3d2b513219341ad88ba2d1b9e5ae/.github/workflows/publish.yaml
```

### Logs

```sh

```

**Comment by Kira-NT** [comment]
Hi! Here `mods.toml` of your mod that got published to Modrinth/CurseForge:

```toml
modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"
[[mods]]
    modId="iguanatweaksreborn"
    version="${file.jarVersion}"
    displayName="Insane's Survival Overhaul"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/iguanatweaks-reborn"
```

Honestly, I'm gonna agree with Modrinth on the fact that `${file.jarVersion}` is not an appropriate version for a mod :D

If you fix your build workflow, so it expands the variables you expect it to expand, mc-publish will infer those values just fine.
