### ISSUE TITLE
[Bug] Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by agus4402** [Kir-Antipov/mc-publish#149]
### Description

```Markdown
Cannot read properties of undefined (reading 'name')" occurs in the GitHub action for uploading to CurseForge. Apparently, the file or project name loads correctly, but at some point in the process, the name property is being accessed from an undefined value.
```

### Expected Behavior

Upload the mod content to github

### Actual Behavior

Action is throwing Error: TypeError: Cannot read properties of undefined (reading 'name') on uploading.

### Version

v3.3

### Environment

GitHub Actions

### Configuration

```yml
- uses: Kir-Antipov/mc-publish@v3.3
          with:
            curseforge-id: ${{ needs.build.outputs.project_id }}
            curseforge-token: ${{ secrets.CF_API_TOKEN }}
            changelog-file: CHANGELOG.md
            java: |
              ${{ needs.build.outputs.java }}
            game-versions: |
              ${{ needs.build.outputs.minecraft_version }}
            files: |
              build/libs/${{ needs.build.outputs.mod_id }}-${{ 
              needs.build.outputs.mod_version }}.jar
            name: ${{ needs.build.outputs.mod_id }}-${{ needs.build.outputs.mod_version }}
            version-type: "${{ needs.build.outputs.release_type }}"
```

### Logs

```sh
Run Kir-Antipov/mc-publish@v3.3
  with:
    curseforge-id: 1217913
    curseforge-token: ***
    changelog-file: CHANGELOG.md
    java: "Java17"
  
    game-versions: 1.20.1
  
    files: build/libs/urumod-0.7-1.20.1.jar
  
    name: urumod-0.7-1.20.1
    modrinth-id: ${undefined}
    modrinth-featured: ${undefined}
    modrinth-unfeature-mode: subset
    modrinth-token: ${undefined}
    github-tag: ${undefined}
    github-generate-changelog: ${undefined}
    github-draft: ${undefined}
    github-prerelease: ${undefined}
    github-commitish: ${undefined}
    github-discussion: ${undefined}
    github-token: ${undefined}
    files-primary: ${undefined}
    files-secondary: ${undefined}
    version: ${undefined}
    changelog: ${undefined}
    loaders: ${undefined}
    dependencies: ${undefined}
    version-resolver: ${undefined}
    game-version-filter: releases
    retry-attempts: 2
    retry-delay: 10000
    fail-mode: fail
    modrinth-files: ${undefined}
    curseforge-files: ${undefined}
    github-files: ${undefined}
    modrinth-files-primary: ${undefined}
    curseforge-files-primary: ${undefined}
    github-files-primary: ${undefined}
    modrinth-files-secondary: ${undefined}
    curseforge-files-secondary: ${undefined}
    github-files-secondary: ${undefined}
    modrinth-name: ${undefined}
    curseforge-name: ${undefined}
    github-name: ${undefined}
    modrinth-version: ${undefined}
    curseforge-version: ${undefined}
    github-version: ${undefined}
    modrinth-version-type: ${undefined}
    curseforge-version-type: ${undefined}
    github-version-type: ${undefined}
    modrinth-changelog: ${undefined}
    curseforge-changelog: ${undefined}
    github-changelog: ${undefined}
    modrinth-changelog-file: ${undefined}
    curseforge-changelog-file: ${undefined}
    github-changelog-file: ${undefined}
    modrinth-loaders: ${undefined}
    curseforge-loaders: ${undefined}
    github-loaders: ${undefined}
    modrinth-game-versions: ${undefined}
    curseforge-game-versions: ${undefined}
    github-game-versions: ${undefined}
    modrinth-dependencies: ${undefined}
    curseforge-dependencies: ${undefined}
    github-dependencies: ${undefined}
    modrinth-version-resolver: ${undefined}
    curseforge-version-resolver: ${undefined}
    github-version-resolver: ${undefined}
    modrinth-game-version-filter: ${undefined}
    curseforge-game-version-filter: ${undefined}
    github-game-version-filter: ${undefined}
    modrinth-java: ${undefined}
    curseforge-java: ${undefined}
    github-java: ${undefined}
    modrinth-retry-attempts: ${undefined}
    curseforge-retry-attempts: ${undefined}
    github-retry-attempts: ${undefined}
    modrinth-retry-delay: ${undefined}
    curseforge-retry-delay: ${undefined}
    github-retry-delay: ${undefined}
    modrinth-fail-mode: ${undefined}
    curseforge-fail-mode: ${undefined}
    github-fail-mode: ${undefined}
📤 Uploading assets to CurseForge
Error: TypeError: Cannot read properties of undefined (reading 'name')
##[debug]Node Action run completed with exit code 1
```

### Other Information

Only happends when i add the name parameter
