### ISSUE TITLE
ArgumentError: At least one loader should be specified to upload files to CurseForge. (Parameter 'request.loaders')

### ISSUE THREAD

**Issue by IMB11** [Kir-Antipov/mc-publish#151]
https://github.com/IMB11/MRU/actions/runs/14195552375/job/39774101999

Not sure why this is suddenly happening?

**Comment by Kira-NT** [comment]
<img alt="stupid mc-publish" src="https://github.com/user-attachments/assets/3b958745-62d8-4909-bc9c-0978d9e66256" width=200>

D:

---

Hey! So, this is *kinda-ish* a duplicate of #130, but not really, because in this case, the issue is triggered by a typo-level mistake on your side that caused your `neoforge.mods.toml` file to have **no** dependencies specified at all.

Here's what you had:

```toml
[["dependencies.mru"]]
modId = "neoforge"
# ...

[["dependencies.mru"]]
modId = "minecraft"
# ...
```

Which is very different from:

```toml
[[dependencies.mru]]
modId = "neoforge"
# ...

[[dependencies.mru]]
modId = "minecraft"
# ...
```

I know. I have no idea why TOML is called "Tom's **Obvious**, Minimal Language" either.

The first snippet translates into:

```json
"dependencies.mru": [
  { "modId": "neoforge" },
  { "modId": "minecraft" }
]
```

While the second one becomes:

```json
"dependencies": {
  "mru": [
    { "modId": "neoforge" },
    { "modId": "minecraft" }
  ]
}
```

Which is the only valid way to specify dependencies for (Neo)Forge *(hence, for mc-publish too)* to recognize them, AFAIK.

So, because your mod metadata didn't have any valid dependencies specified, mc-publish couldn't find the `neoforge` dependency; thus, it wasn't sure whether this was a NeoForge mod; thus, it didn't automatically populate the `loaders` field.

While the last part will be fixed *(since the existence of `neoforge.mods.toml` alone is enough to confirm that it is in fact a NeoForge mod)*, mc-publish still wouldn't be able to identify which Minecraft versions your mod supports, as none were [correctly] specified.

Anyways, hope this helps! :3
