### ISSUE TITLE
[Bug] At least one game version should be specified to upload files to Modrinth.

### ISSUE THREAD

**Issue by ThexXTURBOXx** [Kir-Antipov/mc-publish#155]
### Description

```Markdown
I was using a similar workflow in another project already and it worked fine there. The error does not make any sense as indicated by the logs.
The action log can be found here, if needed: https://github.com/ThexXTURBOXx/BlockHelper/actions/runs/15377508729/job/43264071821
And here is the workflow file: https://github.com/ThexXTURBOXx/BlockHelper/actions/runs/15377508729/workflow

The workflow publishes the mod in three steps: GitHub release first, then Modrinth, then CurseForge (if enabled).
I am using environment variables to specify the value for `game-versions`. The same procedure apparently works fine for `loaders`, but fails for `game-versions` for some reason.
```

### Expected Behavior

The build should be published to Modrinth

### Actual Behavior

The following error is logged:
`Error: ArgumentError: At least one game version should be specified to upload files to Modrinth. (Parameter 'request.gameVersions')`

### Version

"v3"

### Environment

GitHub Actions

### Configuration

```yml
name: Publish

on:
  workflow_dispatch:
    inputs:
      mod_version:
        description: 'Mod Version'
        default: '2.0.0'
        required: true

env:
  MOD_VERSION: ${{ inputs.mod_version }}
  GAME_VERSIONS_CF: ''
  GAME_VERSIONS_MR: |
    b1.1_01
    b1.1_02
  LOADERS_CF: ''
  LOADERS_MR: |
    modloader
  MC_VERSION: b1.1_02

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Download JDK 6
        run: |
          download_url="https://github.com/NicosMinecraftArchive/jdk1.6.0_45/raw/refs/heads/master/jdk-6u45-linux-x64.tar.gz"
          wget -O $RUNNER_TEMP/java_package.tar.gz $download_url

      - name: Set up JDK 6
        uses: actions/setup-java@v4
        with:
          distribution: 'jdkfile'
          jdkFile: ${{ runner.temp }}/java_package.tar.gz
          java-version: '1.6'
          architecture: x64
          mvn-toolchain-vendor: 'Oracle'

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'

      - name: Set mod_version
        run: sed -i -E "s/(mod_version\s*=\s*).+/\1${{ env.MOD_VERSION }}/" gradle.properties

      - name: Build with Gradle
        run: ./gradlew build

      - name: Tag release on GitHub
        uses: Kir-Antipov/mc-publish@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files: LICENSE
          name: ${{ env.MC_VERSION }}-${{ env.MOD_VERSION }}
          version: ${{ env.MC_VERSION }}-${{ env.MOD_VERSION }}
          github-tag: ${{ env.MC_VERSION }}-${{ env.MOD_VERSION }}
          github-commitish: ${{ github.sha }}
          github-generate-changelog: true

      - name: Publish build to Modrinth
        uses: Kir-Antipov/mc-publish@v3
        if: env.GAME_VERSIONS_MR != '' && env.LOADERS_MR != ''
        with:
          modrinth-id: CiDIVfkf
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files: |
            build/libs/*-${{ env.MOD_VERSION }}*.jar
            build/libs/*-${{ env.MOD_VERSION }}*-dev.jar
          name: ${{ env.MC_VERSION }}-${{ env.MOD_VERSION }}
          version: ${{ env.MC_VERSION }}-${{ env.MOD_VERSION }}
          changelog: |
            Full changelog can be found on [GitHub](https://github.com/ThexXTURBOXx/BlockHelper/releases)
          loaders: ${{ env.LOADERS_MR }}
          game-versions: ${{ env.GAME_VERSIONS_MR }}
          java: |
            6
            7
            8

      - name: Publish build to CurseForge
        uses: Kir-Antipov/mc-publish@v3
        if: env.GAME_VERSIONS_CF != '' && env.LOADERS_CF != ''
        with:
          curseforge-id: 251766
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          files: |
            build/libs/*-${{ env.MOD_VERSION }}*.jar
            build/libs/*-${{ env.MOD_VERSION }}*-dev.jar
          name: ${{ env.MC_VERSION }}-${{ env.MOD_VERSION }}
          version: ${{ env.MC_VERSION }}-${{ env.MOD_VERSION }}
          changelog: |
            Full changelog can be found on [GitHub](https://github.com/ThexXTURBOXx/BlockHelper/releases)
          loaders: ${{ env.LOADERS_CF }}
          game-versions: ${{ env.GAME_VERSIONS_CF }}
          java: |
            6
            7
            8
```

### Logs

```sh
Run Kir-Antipov/mc-publish@v3
  with:
    modrinth-id: CiDIVfkf
    modrinth-token: ***
    files: build/libs/*-2.0.0-pre1*.jar
  build/libs/*-2.0.0-pre1*-dev.jar
  
    name: b1.1_02-2.0.0-pre1
    version: b1.1_02-2.0.0-pre1
    changelog: Full changelog can be found on [GitHub](https://github.com/ThexXTURBOXx/BlockHelper/releases)
  
    loaders: modloader
  
    game-versions: b1.1_01
  b1.1_02
  
    java: 6
  7
  8
  
    modrinth-featured: ${undefined}
    modrinth-unfeature-mode: subset
    curseforge-id: ${undefined}
    curseforge-token: ${undefined}
    github-tag: ${undefined}
    github-generate-changelog: ${undefined}
    github-draft: ${undefined}
    github-prerelease: ${undefined}
    github-commitish: ${undefined}
    github-discussion: ${undefined}
    github-token: ${undefined}
    files-primary: ${undefined}
    files-secondary: ${undefined}
    version-type: ${undefined}
    changelog-file: ${undefined}
    dependencies: ${undefined}
    version-resolver: ${undefined}
    game-version-filter: releases
    retry-attempts: 2
    retry-delay: 10000
    fail-mode: fail
    modrinth-files: ${undefined}
    curseforge-files: ${undefined}
    github-files: ${undefined}
    modrinth-files-primary: ${undefined}
    curseforge-files-primary: ${undefined}
    github-files-primary: ${undefined}
    modrinth-files-secondary: ${undefined}
    curseforge-files-secondary: ${undefined}
    github-files-secondary: ${undefined}
    modrinth-name: ${undefined}
    curseforge-name: ${undefined}
    github-name: ${undefined}
    modrinth-version: ${undefined}
    curseforge-version: ${undefined}
    github-version: ${undefined}
    modrinth-version-type: ${undefined}
    curseforge-version-type: ${undefined}
    github-version-type: ${undefined}
    modrinth-changelog: ${undefined}
    curseforge-changelog: ${undefined}
    github-changelog: ${undefined}
    modrinth-changelog-file: ${undefined}
    curseforge-changelog-file: ${undefined}
    github-changelog-file: ${undefined}
    modrinth-loaders: ${undefined}
    curseforge-loaders: ${undefined}
    github-loaders: ${undefined}
    modrinth-game-versions: ${undefined}
    curseforge-game-versions: ${undefined}
    github-game-versions: ${undefined}
    modrinth-dependencies: ${undefined}
    curseforge-dependencies: ${undefined}
    github-dependencies: ${undefined}
    modrinth-version-resolver: ${undefined}
    curseforge-version-resolver: ${undefined}
    github-version-resolver: ${undefined}
    modrinth-game-version-filter: ${undefined}
    curseforge-game-version-filter: ${undefined}
    github-game-version-filter: ${undefined}
    modrinth-java: ${undefined}
    curseforge-java: ${undefined}
    github-java: ${undefined}
    modrinth-retry-attempts: ${undefined}
    curseforge-retry-attempts: ${undefined}
    github-retry-attempts: ${undefined}
    modrinth-retry-delay: ${undefined}
    curseforge-retry-delay: ${undefined}
    github-retry-delay: ${undefined}
    modrinth-fail-mode: ${undefined}
    curseforge-fail-mode: ${undefined}
    github-fail-mode: ${undefined}
  env:
    MOD_VERSION: 2.0.0-pre1
    GAME_VERSIONS_CF: 
    GAME_VERSIONS_MR: b1.1_01
  b1.1_02
  
    LOADERS_CF: 
    LOADERS_MR: modloader
  
    MC_VERSION: b1.1_02
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/21.0.7-6/x64
    JAVA_HOME_1_X64: /opt/hostedtoolcache/Java_jdkfile_jdk/1.6/x64
    JAVA_HOME_21_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/21.0.7-6/x64
📤 Uploading assets to Modrinth
Error: ArgumentError: At least one game version should be specified to upload files to Modrinth. (Parameter 'request.gameVersions')
```
