### ISSUE TITLE
Add a way to create GitHub Releases

### ISSUE THREAD

**Issue by DAmNRelentless** [Kir-Antipov/mc-publish#7]
Is there a way to publish the file as a GitHub pre-release?
I want to have it as a pre-release if it's an alpha or beta.

**Comment by Kir-Antipov** [comment]
This question is not related to the project, it's rather about GitHub Actions themselves, but ok.

It's up to you how to make this work:

 1) Make two different actions for releases and prereleases like so:
    ```yaml
    name: Prerelease
    on:
      release:
        types: [published]

    jobs:
      build:
          if: "github.event.release.prerelease"
          runs-on: ubuntu-latest
          steps:
            # ...
            - uses: Kir-Antipov/mc-publish@v2.1
              with:
                # ...
                version-type: alpha
    ```

    ```yaml
    name: Release
    on:
      release:
        types: [published]

    jobs:
      build:
          if: "!github.event.release.prerelease"
          runs-on: ubuntu-latest
          steps:
            # ...
            - uses: Kir-Antipov/mc-publish@v2.1
              with:
                # ...
                version-type: release
    ```

 2) As an alternative, you can provide a dynamically computed version to the action's input:
    ```yaml
    on:
      release:
        types: [published]

    jobs:
      build:
        # ...
        steps:
          # ...
          - uses: Kir-Antipov/mc-publish@v2.1
            with:
              # ...
              version-type: ${{ some_value_computed_earlier }}
    ```
