### ISSUE TITLE
Generating changelogs for GitHub doesn't seem to work

### ISSUE THREAD

**Issue by Hendrix-Shen** [Kir-Antipov/mc-publish#77]
I tested almost the same configuration on 3.2 and 3.3 (except for the files field) and it worked fine in 3.2, but 3.3 did not generate "Full Changelog: xxx...xxx"

My test workflow config:

``` yml
      ...
      - name: Publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          files: README.md
          github-changelog: |
            **This version is automatically released by CI Build**
            
            Latest commit log:
            
            - ${{ github.event.head_commit.message }}
          github-generate-changelog: true
          github-prerelease: true
          github-commitish: ${{ github.event.ref }}
          github-tag: dev-${{ github.run_number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
```

Did I do something wrong?
