### ISSUE TITLE
Existing github release body is erased when the action is triggered by non-release event

### ISSUE THREAD

**Issue by Fallen-Breath** [Kir-Antipov/mc-publish#90]
## What happened

I have a workflow that utilizes this action. The workflow can be manually triggered with an input tag name to make a patch update for an existing release. When doing so, the existing release body will be erased when the mc-publish action completes

Here's my step config with related params

```yml
      - name: Publish Minecraft Mods
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-tag: ${{ steps.release_info.outputs.tag_name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

          files: ${{ steps.file_info.outputs.path }}
```

Full step config can be found here: https://github.com/Fallen-Breath/fabric-mod-template/blob/4fe395abd6df27728dd77a132b9ae17311b2611c/.github/workflows/release.yml#L158-L187

## Why

The code here set the `changelog` field to an empty string, if the release body doesn't exists in the current github context.

https://github.com/Kir-Antipov/mc-publish/blob/4db8bd126f74d5e143822181a2b1201308e2c796/src/program.ts#L117

Then here's the code that always update the release body

https://github.com/Kir-Antipov/mc-publish/blob/4db8bd126f74d5e143822181a2b1201308e2c796/src/platforms/github/github-uploader.ts#L129-L136

Notes that with the `??=` operatoter, you cannot set a null or undefined value to `github-changelog` to suppress the release body update

## Workaround

Here's some of my workaround for this issue:

- Supply a `github-change` field that contains the current release body, so the release body stays unchanged (it does be updated though, by with the same body content). The release body can be get via other github actions. [example workflow](https://github.com/Fallen-Breath/fabric-mod-template/actions/runs/5988512881/workflow)
- Add a feature to disable github body overwrite, so the existing release body is never touched. See this old issue: #76
