### ISSUE TITLE
HTTP 400 error, when publishing assets to Curseforge

### ISSUE THREAD

**Issue by MagnusHJensen** [Kir-Antipov/mc-publish#93]
When using mc-publish and hitting the upload to CF step, I get the following error, but no description as to why.
<img width="1312" alt="image" src="https://github.com/Kir-Antipov/mc-publish/assets/32039051/4db07a7e-06eb-4e4e-a076-0283d5dca1e6">

I've also tried to run it with debug logging, but no useful error appears.

Github workflow.
```yaml
name: 'Release'

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    name: 'Release'
    steps:
      - uses: actions/checkout@v3
        name: "Checkout Repository"
      - name: "Setup JDK 17"
        uses: actions/setup-java@v3
        with: { distribution: "adopt", java-version: "17" }
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5.1
      - name: Build modules
        id: build
        run: |
          chmod +x gradlew
          ./gradlew :CommonApi:build
          ./gradlew :Forge:build
      - name: Delete unneeded files
        run: |
          rm -rf Forge/build/libs/*-sources.jar
          rm -rf Forge/build/libs/*-javadoc.jar
          rm -rf Forge/build/libs/*-dev.jar
      - name: Release Github Packages
        continue-on-error: true
        id: release-github
        env:
          GITHUB_TOKEN: ${{ secrets.LEGENDS_GITHUB_TOKEN }}
        run: |
          gradle :CommonApi:publish --no-daemon
          gradle :Forge:publish --no-daemon
      - name: Publish Mods
        uses: Kir-Antipov/mc-publish@v3.2
        id: release-mods
        with:
          loaders: |
            forge
          files: Forge/build/libs/*.jar
          modrinth-id: Z43PTXn8
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: 582697
          curseforge-token: ${{ secrets.CURSEFORGE_API_KEY }}
          changelog-file: Forge/changelog.md
      - name: Send webhook
        run: gradle :Forge:sendWebhook --no-daemon ${{ format('-Pcurseforge_file_url={0} -Pmodrinth_file_url={1} -Pdiscord_webhook_url={2}', steps.release-mods.outputs.curseforge-url, steps.release-mods.outputs.modrinth-url, SECRETS.WEBHOOK_URL)  }}

```
